name: contract-builder

services:
  postgres:
    image: postgres
    container_name: contract-builder-postgres
    environment:
      POSTGRES_DB: contract-builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - contract-builder_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  contract-builder_postgres_data:
